"""Purchase Order PDF generator — uses reportlab.

Single entry point: build_po_pdf(po_data) → bytes. Caller is responsible for storing it.
"""
from __future__ import annotations

from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)

BRAND_RED = colors.HexColor("#a02323")
BRAND_DARK = colors.HexColor("#0b1220")
MUTED = colors.HexColor("#6b7280")
LIGHT_GREY = colors.HexColor("#f1f1f1")


def build_po_pdf(po: dict) -> bytes:
    """Render a purchase order PDF from the given data dict.

    Expected shape:
      po_number, generated_at, generated_by_email, generated_by_name,
      for_date, mess_name, supplier_name (optional),
      counts: {full, half, persons, active_subs},
      breakdown: [{label, unit, day_qty, day_cost, lunch_qty, lunch_cost, dinner_qty, dinner_cost, is_amount_based}],
      totals: {lunch_cost, dinner_cost, day_cost},
      notes (optional list of strings)
    """
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=18 * mm, bottomMargin=18 * mm,
        title=f"Purchase Order {po.get('po_number', '')}",
    )

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("H1", parent=styles["Heading1"], textColor=BRAND_DARK, fontSize=22, leading=26, spaceAfter=4)
    overline = ParagraphStyle("Overline", parent=styles["Normal"], textColor=BRAND_RED, fontSize=8, leading=10, fontName="Helvetica-Bold")
    sub = ParagraphStyle("Sub", parent=styles["Normal"], textColor=MUTED, fontSize=10, leading=14)
    cell = ParagraphStyle("Cell", parent=styles["Normal"], fontSize=9, leading=12)
    foot = ParagraphStyle("Foot", parent=styles["Normal"], fontSize=9, leading=14, textColor=MUTED)

    story = []

    # Header
    story.append(Paragraph("EFOODCARE · KITCHEN PROCUREMENT", overline))
    story.append(Paragraph(f"Purchase Order — {po.get('for_date', '')}", h1))
    story.append(Paragraph(f"PO #{po.get('po_number', '')} · generated {po.get('generated_at_local', '')}", sub))
    story.append(Spacer(1, 12))

    # Meta block
    meta_rows = [
        ["For", po.get("for_date", "")],
        ["Mess", po.get("mess_name", "eFoodCare")],
        ["Supplier", po.get("supplier_name") or "—"],
        ["Generated by", f"{po.get('generated_by_name', '')} · {po.get('generated_by_email', '')}"],
        ["Active subscribers", f"{po['counts']['active_subs']} ({po['counts']['full']} full + {po['counts']['half']} half · {po['counts']['persons']} weighted persons)"],
    ]
    meta = Table(meta_rows, colWidths=[35 * mm, None])
    meta.setStyle(TableStyle([
        ("FONT", (0, 0), (0, -1), "Helvetica-Bold", 9),
        ("FONT", (1, 0), (1, -1), "Helvetica", 9),
        ("TEXTCOLOR", (0, 0), (0, -1), MUTED),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(meta)
    story.append(Spacer(1, 14))

    # Breakdown table
    headers = ["Item", "Per person\n/ month", "Rate", "Lunch qty", "Lunch ₹", "Dinner qty", "Dinner ₹", "Day ₹"]
    data = [headers]
    for row in po.get("breakdown", []):
        if row.get("is_amount_based"):
            per_person = f"₹{row.get('amount_per_person_month', 0):.0f}/month"
            rate = "—"
            qty_l = "—"
            qty_d = "—"
        else:
            per_person = f"{row.get('qty_per_person_month', 0):.2f} {row['unit']}"
            rate = f"₹{row.get('price_per_unit', 0):.0f}/{row['unit']}"
            qty_l = f"{(row.get('lunch_qty') or 0):.3f} {row['unit']}"
            qty_d = f"{(row.get('dinner_qty') or 0):.3f} {row['unit']}"
        data.append([
            row["label"],
            per_person,
            rate,
            qty_l,
            f"₹{(row.get('lunch_cost') or 0):.2f}",
            qty_d,
            f"₹{(row.get('dinner_cost') or 0):.2f}",
            f"₹{(row.get('day_cost') or 0):.2f}",
        ])
    totals = po.get("totals", {})
    data.append([
        "TOTAL", "", "", "",
        f"₹{totals.get('lunch_cost', 0):.2f}", "",
        f"₹{totals.get('dinner_cost', 0):.2f}",
        f"₹{totals.get('day_cost', 0):.2f}",
    ])

    col_widths = [33 * mm, 26 * mm, 22 * mm, 22 * mm, 18 * mm, 22 * mm, 18 * mm, 19 * mm]
    table = Table(data, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_RED),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 8),
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
        ("ALIGN", (0, 0), (0, -1), "LEFT"),
        ("FONT", (0, 1), (-1, -2), "Helvetica", 9),
        ("BACKGROUND", (0, -1), (-1, -1), BRAND_DARK),
        ("TEXTCOLOR", (0, -1), (-1, -1), colors.white),
        ("FONT", (0, -1), (-1, -1), "Helvetica-Bold", 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -2), [colors.white, LIGHT_GREY]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d4d4d8")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(table)
    story.append(Spacer(1, 14))

    # Notes
    if po.get("notes"):
        story.append(Paragraph("Notes", ParagraphStyle("NHead", parent=styles["Heading3"], textColor=BRAND_DARK, fontSize=11, leading=14, spaceAfter=4)))
        for n in po["notes"]:
            story.append(Paragraph(f"• {n}", foot))
    story.append(Spacer(1, 24))

    # Signature blocks
    sig = Table(
        [
            ["", ""],
            ["___________________________", "___________________________"],
            ["Issued by", "Received by (supplier)"],
        ],
        colWidths=[None, None],
    )
    sig.setStyle(TableStyle([
        ("FONT", (0, 1), (-1, 1), "Helvetica", 9),
        ("FONT", (0, 2), (-1, 2), "Helvetica-Bold", 9),
        ("TEXTCOLOR", (0, 2), (-1, 2), MUTED),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, 0), 30),
    ]))
    story.append(sig)

    story.append(Spacer(1, 14))
    story.append(Paragraph(
        f"Auto-generated by eFoodCare on {po.get('generated_at_local', datetime.now().isoformat())}. "
        "Quantities are computed from active subscriptions and may shift slightly if subs change before delivery.",
        foot,
    ))

    doc.build(story)
    return buf.getvalue()
